version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  backend:
    image: kuninav/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./data:/app/data

  frontend:
    image: kuninav/foodgram_frontend   
    env_file: .env    
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: kuninav/foodgram_gateway   
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/app/media:ro
      - ./docs:/usr/share/nginx/html/api/docs/
